name: Terraform EKS CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # ✅ Required for OIDC auth
  contents: read         # ✅ Needed to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # ✅ only if your .tf files are in /terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::784434437104:role/GitHubOIDCRole
          aws-region: var.aws_region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
